language: node_js
node_js:
  - "6.1"
install:
  - npm install
  - npm install -g jshint
before_script:
  - npm install -g casperjs
  - phantomjs --version; casperjs --version
script: npm test
notifications:
  email: false