language: node_js
node_js:
  - "6.1"
before_install:
  - git submodule update --init --recursive
install:
  - npm install
  - npm install jshint
before_script:
  - npm install -g casperjs
  - phantomjs --version; casperjs --version
script: npm test
notifications:
  email: false